name: "gobump-deps"
description: "Bump Go project dependencies using lzap/gobump and open a PR"
branding:
  icon: "box"
  color: "orange"
inputs:
  go_version:
    description: "Go version to use when setup_go is true (defaults: stable)"
    required: false
    default: "stable"
  token:
    description: "GitHub token with permissions to push branches and open PRs"
    required: true
  exec:
    description: "String to pass via gobump -exec argument (no shell expansion)"
    required: false
  exec2:
    description: "Additional string to pass via gobump -exec argument (no shell expansion)"
    required: false
  labels:
    description: "Comma-separated list of labels to add to the PR"
    required: false
  tidy:
    description: "Run go mod tidy after bumping dependencies (default: true)"
    required: false
    default: "true"
  setup_go:
    description: "Set up Go environment (default: true)"
    required: false
    default: "true"
  exec_pr:
    description: "Command to execute before PR is made (bash shell)"
    required: false
  pr:
    description: "Create a pull request with the changes"
    required: false
    default: "true"
  development:
    description: "Run in development mode and build from the current repo (default: false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Go environment
      if: ${{ inputs.setup_go == 'true' }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
        cache: 'true'
        cache-dependency-path: '**/go.sum'

    - name: Bump dependencies with latest version
      if: ${{ inputs.development == 'false' }}
      shell: bash
      env:
        GOTOOLCHAIN: local
      run: |
        go version
        go env
        go run github.com/lzap/gobump@latest -exec "${{ inputs.exec }}" -exec "${{ inputs.exec2 }}" | tee /tmp/bump.log

    - name: Prepare development environment
      if: ${{ inputs.development == 'true' }}
      shell: bash
      env:
        GOTOOLCHAIN: local
      run: |
        go version
        go env
        go get -v ./...

    - name: Bump dependencies with development version
      if: ${{ inputs.development == 'true' }}
      shell: bash
      env:
        GOTOOLCHAIN: local
      run: |
        go run . -exec "${{ inputs.exec }}" -exec "${{ inputs.exec2 }}" | tee /tmp/bump.log

    - name: Run go mod tidy
      if: ${{ inputs.tidy == 'true' }}
      shell: bash
      env:
        GOTOOLCHAIN: local
      run: |
        go mod tidy

    - name: Execute command before PR
      shell: bash
      if: ${{ inputs.exec_pr != '' }}
      run: ${{ inputs.exec_pr }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      if: ${{ inputs.pr == 'true' }}
      with:
        token: ${{ inputs.token }}
        branch: "gobump-deps-${{ github.run_id }}"
        commit-message: "chore: bump Go dependencies"
        title: "chore: bump dependencies via gobump"
        body-path: /tmp/bump.log
        labels: ${{ inputs.labels }}
