name: "gobump-deps"
description: "Bump Go project dependencies using lzap/gobump and open a PR"
branding:
  icon: "box"
  color: "orange"
inputs:
  token:
    description: "GitHub token with permissions to push branches and open PRs"
    required: true
  exec:
    description: "String to pass via gobump -exec argument (no shell expansion)"
    required: false
  exec2:
    description: "Additional string to pass via gobump -exec argument (no shell expansion)"
    required: false
  labels:
    description: "Comma-separated list of labels to add to the PR"
    required: false
  tidy:
    description: "Run go mod tidy after bumping dependencies (default: true)"
    required: false
    default: "true"
  setup_go:
    description: "Set up Go environment (default: true)"
    required: false
    default: "true"
  pr:
    description: "Create a pull request with the changes"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Go environment
      if: ${{ inputs.setup_go == 'true' }}
      uses: actions/setup-go@v5

    - name: Install gobump
      shell: bash
      run: |
        go install github.com/lzap/gobump@latest

    - name: Bump dependencies
      shell: bash
      run: |
        go run github.com/lzap/gobump@latest -exec "${{ inputs.exec }}" -exec "${{ inputs.exec2 }}" > bump.log

    - name: Run go mod tidy
      if: ${{ inputs.tidy == 'true' }}
      shell: bash
      run: |
        go mod tidy

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      if: ${{ inputs.pr == 'true' }}
      with:
        token: ${{ inputs.token }}
        branch: "gobump-deps-${{ github.run_id }}"
        commit-message: "chore: bump Go dependencies"
        title: "chore: bump dependencies via gobump"
        body-path: bump.log
        labels: ${{ inputs.labels }}
