name: "gobump-deps"
description: "Bump Go project dependencies using lzap/gobump and open a PR"
inputs:
  token:
    description: "GitHub token with permissions to push branches and open PRs"
    required: true
  exec:
    description: "String to pass via gobump -exec argument (no shell expansion)"
    required: false
  labels:
    description: "Comma-separated list of labels to add to the PR"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Go environment
      uses: actions/setup-go@v5

    - name: Install gobump
      shell: bash
      run: |
        go install github.com/lzap/gobump@latest

    - name: Bump dependencies
      shell: bash
      run: |
        if [ -n "${{ inputs.exec }}" ]; then
          go run github.com/lzap/gobump@latest -exec "${{ inputs.exec }}" > bump.log
        else
          go run github.com/lzap/gobump@latest
        fi

    - name: Run go mod tidy
      shell: bash
      run: |
        go mod tidy

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        branch: "gobump-deps-${{ github.run_id }}"
        commit-message: "chore: bump Go dependencies"
        title: "chore: bump dependencies via gobump"
        body-path: bump.log
        labels: ${{ inputs.labels }}
