name: "Tests"
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  bump-deps-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gobump-deps action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exec: "go build ."
          exec2: "go test ."
          labels: "ubuntu"
          exec_pr: "echo 'Running before PR command'"
          pr: false

  bump-deps-fedora:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:42
    steps:
      - name: Set up the environment
        run: "sudo dnf -y install git gh golang"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gobump-deps action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exec: "go build ."
          exec2: "go test ."
          labels: "fedora"
          exec_pr: "echo 'Running before PR command'"
          pr: false
          setup_go: false
  
