name: "Tests"
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  bump-deps-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gobump-deps action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exec: "go build -buildvcs=false ."
          exec2: "go test -buildvcs=false ."
          exec_pr: "ls -lah1"
          pr: false
          development: true

  bump-deps-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gobump-deps action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          include: "github.com/google/go-cmp"
          exec: "go build -buildvcs=false ."
          exec_pr: "ls -lah1"
          pr: false
          development: true
          
  bump-deps-fedora:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:42
    steps:
      - name: Set up the environment
        run: "sudo dnf -y install git gh"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gobump-deps action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exec: "go build -buildvcs=false ."
          exec2: "go test -buildvcs=false ."
          exec_pr: "ls -lah1"
          pr: false
          development: true
